const TRANSACTION_TYPE = 'ARC01';
const NOTE_BYTE_LIMIT = 1000;
const OPERATION_NAMES = {
  CREATE: 'CREATE',
  REQUEST_TRANSFER: 'REQUEST_TRANSFER',
  APPROVE_TRANSFER: 'APPROVE_TRANSFER',
  DENY_TRANSFER: 'DENY_TRANSFER',
  UPDATE_COMPLIANCE: 'UPDATE_COMPLIANCE',
  ADD_DOCUMENT: 'ADD_DOCUMENT',
  UPDATE_DISTRIBUTION: 'UPDATE_DISTRIBUTION',
};

module.exports = {
  TRANSACTION_TYPE,
  OPERATION_NAMES,
  NOTE_BYTE_LIMIT,
};
